### ISSUE TITLE
버그 및 TODO 작성

### ISSUE THREAD

**Issue by whdgur5717** [side-peek/sidepeek_frontend#182]
### 공통

- 버그 or 수정 사항들을 적어주세요 (Edit눌러서 taskList 방식으로 적어주세요 댓글X!!)
- [ ] 메인 페이지 접속 시 API 요청이 두번 되어서 화면이 두번 깜빡임

### 종혁
- [ ] hook-form -> zustand로 변경해서 폼에 대한 유효성 검사 필요
- [ ] 수정 요청 접근 시 해당 유저인지 판단하기

### 승민

 [ ] 

### 훈오

- [ ] 모든 페이지 진입시 스크롤 맨위로

### 동건

 [ ] 

### 민호

 [ ]
